Result for test_case/func_arg_test/test_func_arg.py:
======[pikapython packages installed]======
pikascript-core==v1.13.3 (2024/05/25 01:26:44)
PikaStdLib===v1.13.3
time===v0.2.2
===========================================
~~~/ POWERED BY \~~~
~  pikapython.com  ~
~~~~~~~~~~~~~~~~~~~~
hello pikascript
>>> def test_function_arguments(a, b=2, *args, **kwargs):
...     print("a:", a)
...     print("b:", b)
...     print("*args:", args)
...     print("**kwargs:", kwargs)
... 
>>> print('======= Test Start =======')
======= Test Start =======
>>> print("\nTest function: test_function_arguments(a, b=2, *args, **kwargs)")
Test function: test_function_arguments(a, b=2, *args, **kwargs)
>>> print("\nFunction arguments test:")
Function arguments test:
>>> test_function_arguments(1)
a: 1
b: 2
*args: ()
**kwargs: {}
>>> test_function_arguments(1, 3)
a: 1
b: 2
*args: (3,)
**kwargs: {}
>>> test_function_arguments(1, 3, 4, 5, 6)
a: 1
b: 2
*args: (3, 4, 5, 6)
**kwargs: {}
>>> test_function_arguments(1, 3, 4, 5, 6, x=7, y=8)
a: 1
b: 2
*args: (3, 4, 5, 6)
**kwargs: {'177693': 7, '177694': 8}
>>> print("\nFunction arguments test with keyword arguments:")
Function arguments test with keyword arguments:
>>> test_function_arguments(a=1)
a: 1
b: 2
*args: ()
Assertion "self != 0" failed, in function: arg_getType(). 
  (at /home/azhao/LeafScript/PikaPython/build/linux/../../src/dataArg.h:140)
Aborted
